export enum ECompanySector {
    AGRICULTURA = "Agricultura",
    AUTOMOTIVO = "Automotivo",
    AVIACAO = "Aviação",
    BANCARIO = "Bancário",
    CONSTRUCAO = "Construção",
    CONSULTORIA = "Consultoria",
    EDUCACAO = "Educação",
    ENERGIA = "Energia",
    ENTRETENIMENTO = "Entretenimento",
    MEIO_AMBIENTE = "Meio Ambiente",
    MODA = "Moda",
    FINANCAS = "Finanças",
    ALIMENTOS_BEBIDAS = "Alimentos e Bebidas",
    GOVERNO = "Governo",
    SAUDE = "Saúde",
    HOSPITALIDADE = "Hospitalidade",
    TECNOLOGIA_INFORMACAO = "Tecnologia da Informação",
    SEGUROS = "Seguros",
    JURIDICO = "Jurídico",
    LOGISTICA = "Logística",
    MANUFATURA = "Manufatura",
    MARKETING = "Marketing",
    MIDIA = "Mídia",
    MINERACAO = "Mineração",
    SEM_FINS_LUCRATIVOS = "Sem Fins Lucrativos",
    FARMACEUTICO = "Farmacêutico",
    IMOBILIARIO = "Imobiliário",
    VAREJO = "Varejo",
    ESPORTES = "Esportes",
    TELECOMUNICACOES = "Telecomunicações",
    TURISMO = "Turismo",
    TRANSPORTE = "Transporte",
    SERVICOS_PUBLICOS = "Serviços Públicos",
    GERENCIAMENTO_RESIDUOS = "Gerenciamento de Resíduos",
    OUTROS = "Outros"
  }
  